### ISSUE TITLE
Implement custom GUI leveraging the Mekanism-inspired architecture

### ISSUE THREAD

**Issue by ax-vasquez** [ax-vasquez/enchantments-seer#32]
# Description
This is one of the "core" challenges for the mod. This change will make it so that the Seer's Enchanting Table GUI has all of the elements a player will need in order to use this mod.

## General usage guide
Enchanting should be pretty straight-forward:
1. Player provides an item to enchant - _the enchantment list does nothing until a reagent is provided_
2. Seer's Enchanting Table does _something_ depending on the provided reagent:
    1. **Seer's Stone:** - _2 conditions, but in either case, nothing renders in the list area_
        a. _Enchanted Item: The "Seer's Stone" recharge cost is displayed; partial recharging should be allowed_
        b. _Regular Item: A "No effect" message should display; helps to guide the user in how to use the mod. Should instruct the user to provide an enchanted item, or to enchant the given item before it will work_
    2. **Seer's Manuscript:** - _Full list of enchantments for the given item is rendered (unless the item is already enchanted, in which case, nothing should be displayed other than a message saying "the item is already enchanted"_
    3. **Arbitrary enchanted book:** - _Filtered list of enchantments in the scroll list; only enchantments applied to the book are listed, **and only if the enchantment is applicable to the given item**_.

> It might not be a bad idea to include a tooltip that lets the user know that it's possible for enchantments to "disappear" from the list. For example, if you provide no item to enchant, but have a Seer's Manuscript in the reagent slot, all enchantments will display. However, once you provide a specific item to enchant, _the list should update to only show enchantments that can actually be applied to the item._ This mod does not override item enchantment compatibility.

## Tasks
Implement a GUI that enables all of the following:
1. [ ] **Has two Item input slots**
    1. [ ] **Enchant item input** - _Should allow any arbitrary item_
    2. [ ] **Reagent input** - _Should allow Seer's Stone(s), Seer's Manuscript, or arbitrary enchanted book_
2. [ ] **Has a scrolling list for all enchantments available for the enchant item**
    1. [ ] **List only shows enchants available for the current item**
    2. [ ] **List is empty when there are no items in the enchant slot**
    3. [ ] **List Item design**
        1. [ ] **Clear-text name for enchantment**
        2. [ ] **Clear-text label for enchantment level (I, II, III, IV, etc.)**
        3. [ ] **Horizontal slider** - _This is how the player will control the level of the enchant they want to use_

**Comment by ax-vasquez** [comment]
In order to not have to write too much extra crap, we should model the logic for the GUI after the base enchanting table.

In effect, the end result should be a **Vanilla-inspired enchanting GUI built using the Mekanism architecture.** 

This will inevitably result in need to pull in/extract logic from the Vanilla codebase, most likely from:
1. `EnchantmentContainer` (presumably one enchantment per container here)
2. `EnchantingTableBlock` - just for reference
3. `EnchantingTableTileEntity`
4. `SimpleNamedContainerProvider`

## Vanilla Enchantment table GUI discussion
* `EnchantingTableBlock#getMenuProvider(BlockState, World, BlockPos)` is responsible for "linking" the block to a menu
    * The `EnchantingTableBlock#use(BlockState, World, BlockPos, PlayerEntity, Hand, BlockRayTraceResult)` is responsible for actually opening the linked menu
    * `getMenuProvider` is called within `use`, **but only if opened from the server side**

### `EnchantingTableBlock#getMenuProvider`
This method is responsible for returning the menu container provider. Presumably, the provider is _invoked_ when the user attempts to open the menu, meaning **the menu object is not statically-stored, but rather "provided" to the user on-request.**

`SimpleNamedContainerProvider`'s first argument implements the `IContainerProvider` interface, which gives it the `createMenu` method. Create menu takes three arguments; the first two are `int`s and the last is a `PlayerEntity`. Since the code is deobfuscated, it's not clear what the name should be, but judging from how Mekanism has overridden similar methods, I'm guessing the arguments are (in this order):
1. `x` - the width of the GUI container to draw
2. `y` - the height of the GUI container to draw
3. `player` - the player requesting the menu to be provided to them

The following snippet is from `EnchantingTableBlock#getMenuProvider`:
```java
@Nullable
public INamedContainerProvider getMenuProvider(BlockState blockState, World worldIn, BlockPos blockPos) {
      TileEntity tileentity = worldIn.getBlockEntity(blockPos);
      if (tileentity instanceof EnchantingTableTileEntity) {
         ITextComponent itextcomponent = ((INameable)tileentity).getDisplayName();
         return new SimpleNamedContainerProvider((x, y, player) -> {
            return new EnchantmentContainer(x, y, IWorldPosCallable.create(worldIn, blockPos));
         }, itextcomponent);
      } else {
         return null;
      }
}
```
* Seems the "key" for their implementation is to return an `INamedContainerProvider` in order to open a menu

**Comment by ax-vasquez** [comment]
# Mekanism vs Vanilla GUI systems

| Concept/Feature | Minecraft | Mekanism |
| ----------------- | ---------- | ---------- |
| **Texture(s)** | All texture assets for a given GUI are contained in the corresponding, purpose-built texture file; this makes  texture manipulation logic (using `blit` methods) highly-complex and custom for each image used | "Composes" GUIs using pre-defined assets; there are no "gui-specific" image files - GUI images are all generic and meant to work together for a variety of use cases |
| **Inventory Slots** | Each `*Screen` class (e.g., `EnchantmentScreen`) seems to individually draw the inventory slots; lots of repeat code | Base `GuiMekanism` class defines `addSlots`, which handles inventory slots for all subclasses; _as a result, the GUI classes that actually get registered are far simpler and easier to understand |
| **HotBar Slots** |
